name: Go package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      # To get git to work in the tests
      - name: Set git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "test@test.com"

      - name: Test with Go ${{ matrix.go-version }}
        run: go test
